// ⚠️ COMPILA QUESTI VALORI DAL TUO PROGETTO SUPABASE
export const SUPABASE_URL = 'https://jhsyryhksfdfaxmykgvx.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impoc3lyeWhrc2ZkZmF4bXlrZ3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1ODE5ODUsImV4cCI6MjEwNTE1Nzk4NX0.mPXBL-y5HVlD0IzT5NPO-jxN9n-evg7ZbmFx-bofRHo';
